sylius_twig_hooks:
    hooks:
        'sylius_admin.product_variant.update.content.form.side_navigation':
            esd:
                template: '@SyliusAdyenPlugin/admin/product_variant/form/side_navigation/esd.html.twig'
                priority: -100

        'sylius_admin.product_variant.update.content.form.sections':
            esd:
                template: '@SyliusAdyenPlugin/admin/product_variant/form/sections/esd.html.twig'
                priority: -100

        'sylius_admin.product_variant.update.content.form.sections.esd':
            commodity_code:
                template: '@SyliusAdyenPlugin/admin/product_variant/form/sections/esd/commodity_code.html.twig'
                priority: 0
