framework:
    workflows:
        sylius_payment:
            places:
                - processing_reversal
            transitions:
                capture:
                    from: [new, processing, authorized]
                    to: completed
                reverse:
                    from: [completed]
                    to: processing_reversal
#                fail:
#                    from: completed
#                    to: failed
#                process:
#                    from: authorized
#                    to: processing
#                cancel:
#                    from: processing_reversal
#                    to: cancelled
#                refund:
#                    from: processing_reversal
#                    to: refunded
