#framework:
#    workflows:
#        sylius_order_payment:
#            transitions:
#                request_payment:
#                    from: [authorized, paid]
#                    to: awaiting_payment
#                cancel:
#                    from: [paid]
#                    to: cancelled
