sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.header.title_block.actions.list':
            adyen_refund:
                template: '@SyliusAdyenPlugin/admin/order/content/header/title_block/actions/refund.html.twig'
                priority: -100

        'sylius_admin.order.show.content.sections.payments.item.actions':
            adyen_complete:
                template: '@SyliusAdyenPlugin/admin/order/content/sections/payments/item/actions/complete.html.twig'
                priority: 100
            adyen_capture:
                template: '@SyliusAdyenPlugin/admin/order/content/sections/payments/item/actions/capture.html.twig'
                priority: 100
            adyen_send_payment_link:
                template: '@SyliusAdyenPlugin/admin/order/content/sections/payments/item/actions/send_payment_link.html.twig'
                priority: 100
