sylius_twig_hooks:
    hooks:
        'sylius_shop.checkout.select_payment.content.form.select_payment.payment.choice.adyen.details':
            brands:
                template: '@SyliusAdyenPlugin/shop/checkout/select_payment/content/form/select_payment/payment/choice/details/brands.html.twig'
                priority: -100
