sylius_adyen_shop_express_checkout_cart_configuration:
    path: /adyen/express-checkout/cart-configuration
    methods: [GET]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.cart_configuration

sylius_adyen_shop_express_checkout_google_pay_shipping_options:
    path: /adyen/express-checkout/google-pay/shipping-options
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.google_pay.shipping_options

sylius_adyen_shop_express_checkout_google_pay_checkout:
    path: /adyen/express-checkout/google-pay/checkout
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.google_pay.checkout

sylius_adyen_shop_express_checkout_paypal_initialize:
    path: /adyen/express-checkout/paypal/initialize
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.paypal.initialize

sylius_adyen_shop_express_checkout_paypal_shipping_address_change:
    path: /adyen/express-checkout/paypal/shipping-address-change
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.paypal.shipping_address_change

sylius_adyen_shop_express_checkout_paypal_shipping_options_change:
    path: /adyen/express-checkout/paypal/shipping-options-change
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.paypal.shipping_options_change

sylius_adyen_shop_express_checkout_paypal_checkout:
    path: /adyen/express-checkout/paypal/checkout
    methods: [POST]
    defaults:
        _controller: sylius_adyen.controller.shop.express_checkout.paypal.checkout

sylius_adyen_shop_express_checkout_apple_pay_shipping_address_change:
  path: /adyen/express-checkout/apple-pay/shipping-address-change
  methods: [POST]
  defaults:
    _controller: sylius_adyen.controller.shop.express_checkout.apple_pay.shipping_address_change

sylius_adyen_shop_express_checkout_apple_pay_shipping_options_change:
  path: /adyen/express-checkout/apple-pay/shipping-options-change
  methods: [POST]
  defaults:
    _controller: sylius_adyen.controller.shop.express_checkout.apple_pay.shipping_options_change
