sylius_twig_hooks:
    hooks:
        'sylius_admin.product.create.content.form.sections.general':
            commodity_code:
                template: '@SyliusAdyenPlugin/admin/product/form/sections/general/commodity_code.html.twig'
                priority: -100
