Sylius\AdyenPlugin\Resolver\Notification\Struct\NotificationItem:
  properties:
    notificationRequestItem:
      - Valid: ~

Sylius\AdyenPlugin\Resolver\Notification\Struct\Amount:
  properties:
    currency:
      - NotBlank: ~
    value:
      - GreaterThanOrEqual: 0

Sylius\AdyenPlugin\Resolver\Notification\Struct\NotificationItemData:
  constraints:
    - Sylius\AdyenPlugin\Validator\Constraint\HmacSignature: ~
  properties:
    eventCode:
      - NotBlank: ~
    merchantReference:
      - NotBlank: ~
    pspReference:
      - NotBlank: ~
    amount:
      - Valid: ~
      - NotBlank: ~
