sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.index.content.header.title_block.actions':
            adyen:
                template: '@SyliusAdyenPlugin/admin/payment_method/index/content/header/title_block/actions/adyen.html.twig'
                configuration:
                    items:
                        - title: 'sylius_adyen.ui.logs'
                          path: 'sylius_adyen_admin_log_index'
                priority: 0
