#sylius_ui:
#    events:
#        sylius.shop.layout.stylesheets:
#            blocks:
#                adyen:
#                    template: '@SyliusAdyenPlugin/Shop/_stylesheets.html.twig'
#        sylius.shop.layout.javascripts:
#            blocks:
#                adyen:
#                    template: '@SyliusAdyenPlugin/Shop/_javascripts.html.twig'
#                adyen_analytics:
#                    template: '@SyliusAdyenPlugin/Shop/_analytics.html.twig'
#
#        sylius.shop.cart.summary:
#            blocks:
#                express_checkout:
#                    template: "@SyliusAdyenPlugin/Shop/Cart/Summary/express_checkout.html.twig"
#                    priority: -10
#
#        sylius.shop.cart.summary.adyen_express_checkout:
#            blocks:
#                apple_pay:
#                    template: "@SyliusAdyenPlugin/Shop/Cart/Summary/ExpressCheckout/apple_pay.html.twig"
#                    priority: 200
#                google_pay:
#                    template: "@SyliusAdyenPlugin/Shop/Cart/Summary/ExpressCheckout/google_pay.html.twig"
#                    priority: 100
#                paypal:
#                    template: "@SyliusAdyenPlugin/Shop/Cart/Summary/ExpressCheckout/paypal.html.twig"
#                    priority: 0
#
#        sylius.shop.product.show.right_sidebar:
#            blocks:
#                express_checkout:
#                    template: "@SyliusAdyenPlugin/Shop//Product/Show/express_checkout.html.twig"
#                    priority: -10
#
#        sylius.shop.product.show.right_sidebar.adyen_express_checkout:
#            blocks:
#                apple_pay:
#                    template: "@SyliusAdyenPlugin/Shop/Product/Show/ExpressCheckout/apple_pay.html.twig"
#                    priority: 200
#                google_pay:
#                    template: "@SyliusAdyenPlugin/Shop//Product/Show/ExpressCheckout/google_pay.html.twig"
#                    priority: 100
#                paypal:
#                    template: "@SyliusAdyenPlugin/Shop//Product/Show/ExpressCheckout/paypal.html.twig"
#                    priority: 0
