name: Build

on:
    push:
        branches-ignore:
            - 'dependabot/**'
            - 'upmerge/**'
        paths-ignore:
            - "doc/**"
            - "*.md"
    pull_request:
        paths-ignore:
            - "doc/**"
            - "*.md"
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * *" # Run at 1am every day
    workflow_dispatch: ~

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, ${{ matrix.database == 'mysql' && format('MySQL {0}', matrix.database_version) || format('PostgreSQL {0}', matrix.database_version) }}, State Machine Adapter ${{ matrix.state_machine_adapter }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.3"]
                symfony: ["^6.4", "^7.4"]
                sylius: ["~2.0.0", "~2.1.0", "~2.2.0"]
                node: ["22.x"]
                database: ["mysql"]
                database_version: ["8.4"]
                state_machine_adapter: ["symfony_workflow"]

                include:
                    -
                        php: "8.2"
                        symfony: "^6.4"
                        sylius: "~2.1.0"
                        node: "22.x"
                        database: "mysql"
                        database_version: "8.4"
                        state_machine_adapter: "winzou_state_machine"

                    -
                        php: "8.3"
                        symfony: "^7.4"
                        sylius: "~2.1.0"
                        node: "22.x"
                        database: "postgres"
                        database_version: "15.8"
                        state_machine_adapter: "symfony_workflow"

        env:
            APP_ENV: test
            DATABASE_URL: ${{ matrix.database == 'mysql' && format('mysql://root:root@127.0.0.1/sylius?serverVersion={0}', matrix.database_version) || format('pgsql://postgres:postgres@127.0.0.1/sylius?serverVersion={0}', matrix.database_version) }}
            TEST_SYLIUS_STATE_MACHINE_ADAPTER: "${{ matrix.state_machine_adapter }}"

        steps:
            -
                uses: actions/checkout@v4

            -
                name: Require Winzou State Machine
                if: "${{ matrix.state_machine_adapter == 'winzou_state_machine' }}"
                run: |
                    composer require winzou/state-machine:^0.4 --no-update
                    composer require winzou/state-machine-bundle:^0.6 --no-update

            -
                name: Build Sylius Test Application
                uses: SyliusLabs/BuildTestAppAction@v3.2.0
                with:
                    e2e_js: "yes"
                    cache_key: "${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
                    cache_restore_key: "${{ runner.os }}-php-${{ matrix.php }}-composer-"
                    database: "${{ matrix.database }}"
                    database_version: "${{ matrix.database_version }}"
                    node_version: "${{ matrix.node }}"
                    php_version: "${{ matrix.php }}"
                    sylius_version: "${{ matrix.sylius }}"
                    symfony_version: "${{ matrix.symfony }}"

            -
                name: Setup Messenger transports
                run: vendor/bin/console messenger:setup-transports

            -
                name: Generate test application encryption key
                run: vendor/bin/console sylius:payment:generate-key -n

            -
                name: Run security check
                run: composer audit --abandoned=ignore

            -
                name: Validate composer.json
                run: composer validate --ansi --strict

            -
                name: Run ECS
                run: vendor/bin/ecs check

            -
                name: Lint container
                run: vendor/bin/console lint:container

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse

            -
                name: Run PHPUnit (Unit)
                run: vendor/bin/phpunit --colors=always --testsuite=unit

            -
                name: Run PHPUnit (Functional)
                run: vendor/bin/phpunit --colors=always --testsuite=functional

            -
                name: Run Behat
                run: vendor/bin/behat --tags="~@todo" --colors --strict -vvv --no-interaction || vendor/bin/behat --tags="~@todo" --colors --strict -vvv --no-interaction --rerun

            -
                name: Upload Behat logs
                uses: actions/upload-artifact@v4
                if: failure()
                with:
                    name: "Behat logs - Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, ${{ matrix.database }} ${{ matrix.database_version }}"
                    path: |
                        etc/build/
                        var/log
                    if-no-files-found: ignore
                    compression-level: 6
                    overwrite: true
